name: Release Please

on:
  workflow_call:
    inputs: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Fetch shared config
        uses: actions/checkout@v4
        with:
          repository: CloudRader/ci-templates
          path: ci-templates

      # --------------------
      # Debug steps
      # --------------------
      - name: Debug print directory tree
        run: |
          pwd
          ls -R .

      - name: Debug show .github folder
        run: |
          ls -R .github || true

      - name: Debug show ci-templates folder
        run: |
          ls -R ci-templates || true

      - uses: googleapis/release-please-action@v4
        with:
          target-branch: main
          config-file: ci-templates/configs/release-please/release-please-config.json
          manifest-file: ci-templates/configs/release-please/.release-please-manifest.json
